Users/annautiy/pre download v2
microsoft/PackageUploader pull request #46
Opened 2024-05-18 20:44 UTC by Annautiy

2024-05-28 11:42 UTC, alberto-baron requested changes
We try to make this tool usage as easy as possible so improving validation and exposing the right methods and classes in the ClientApi is important for integrations. 
Added a few changes to try achieve that

2024-05-28 11:42 UTC, alberto-baron commented on Operations.md
> +- **packageMetadata**: optional - if informed it will configure custom metadata for your XVC/MSIXVC packages. It supports the following properties
In order to simplify validation and usage, we should be using the same pattern as availabilityDate here, with a isEnabled and effectiveDate.

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.Application/Config/ImportPackagesOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
This should be a GamePackageDate to be able to validate and give a correct error message

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.Application/Config/UploadXvcPackageOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
this should be a GamePackageDate to be able to validate and give a correct error message

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.Application/Operations/ImportPackagesOperation.cs
> +        await _storeBrokerService.ImportPackagesAsync(product, originPackageBranch, destinationPackageBranch, _config.MarketGroupName, _config.Overwrite, _config, _config.GetMarketGroupPackageMetadat
logic conversion from preDownloadDate to PackageMetadata should be done in the ClientApi

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.Application/Operations/UploadXvcPackageOperation.cs
> +            await _storeBrokerService.SetXvcAvailabilityDateAndPackageMetadataAsync(product, packageBranch, gamePackage, _config.MarketGroupName, _config.AvailabilityDate, _config.GetMarketGroupPacka
logic conversion from preDownloadDate to PackageMetadata should be done in the ClientApi

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/GameMarketGroupPackage.cs
> +    /// Dictionary of per package metadata (e.g. predownload date) for XVC and MSIXVC packages
is this per region, same as availability dates?

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/MarketGroupPackageMetadata.cs
> +    public Dictionary<string, object> JsonExtensionData { get; set; }
this is external facing model, it should not be using objects, should be named properties so customers can inform them knowing what they are
conversion to internal can be done in mapping class

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/MarketGroupPackageMetadata.cs
> +    [JsonExtensionData]
is this object serialized?

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.ClientApi/IPackageUploaderService.cs
> +    Task<GamePackageConfiguration> SetXvcAvailabilityDateAndPackageMetadataAsync(GameProduct product, IGamePackageBranch packageBranch, GamePackage gamePackage, string marketGroupName, GamePackageDat
instead of MarketGroupPackageMetadata we should be receiving GamePackageDate preDownloadDate

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.ClientApi/IPackageUploaderService.cs
> +    Task<GamePackageConfiguration> ImportPackagesAsync(GameProduct product, IGamePackageBranch originPackageBranch, IGamePackageBranch destinationPackageBranch, string marketGroupName, bool overwrite
instead of MarketGroupPackageMetadata we should be receiving GamePackageDate preDownloadDate

2024-05-28 11:42 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +    public async Task<GamePackageConfiguration> SetXvcAvailabilityDateAndPackageMetadataAsync(GameProduct product, IGamePackageBranch packageBranch, GamePackage gamePackage, string marketGroupName, G
maybe we should extract MandatoryDate  and GradualRollout  from GamePackageConfiguration to its own UwpGamePackageConfiguration inheriting from GamePackageConfiguration and create a XvcGamePackageConfiguration inheriting from GamePackageConfiguration with preDownloadDate on it and have that as a parameter here instead

2024-05-29 15:53 UTC, Annautiy commented on Operations.md
> +- **packageMetadata**: optional - if informed it will configure custom metadata for your XVC/MSIXVC packages. It supports the following properties
So, packageMetadata currently only support preDownloadDate. But can have any other properties also in future. 

Thus, to follow same pattern as availabilityDate I can use IsEnabled and whole packageMetadata. Please, update if it looks fine and will change accordingly.

2024-05-29 15:55 UTC, Annautiy commented on src/PackageUploader.Application/Config/ImportPackagesOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
So, packageMetadata currently only support preDownloadDate. But can have any other properties also in future. Thus, same was added

2024-05-29 15:56 UTC, Annautiy commented on src/PackageUploader.Application/Config/UploadXvcPackageOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
So, packageMetadata currently only support preDownloadDate. But can have any other properties also in future. Thus, same was added

2024-05-29 15:58 UTC, Annautiy commented on src/PackageUploader.Application/Operations/ImportPackagesOperation.cs
> +        await _storeBrokerService.ImportPackagesAsync(product, originPackageBranch, destinationPackageBranch, _config.MarketGroupName, _config.Overwrite, _config, _config.GetMarketGroupPackageMetadat
So, _config being passed to ClientApi is base class which can't support same. I can't pass child class as same is marked as internal. Thus, conversion is added here.

2024-05-29 16:05 UTC, Annautiy commented on src/PackageUploader.Application/Operations/UploadXvcPackageOperation.cs
> +            await _storeBrokerService.SetXvcAvailabilityDateAndPackageMetadataAsync(product, packageBranch, gamePackage, _config.MarketGroupName, _config.AvailabilityDate, _config.GetMarketGroupPacka
The configuration object being passed to ClientApi is a base class, which does not support the required functionality. Unfortunately, it is not feasible to pass a derived class as it is marked as internal. Therefore, a conversion has been implemented at this juncture.

Regarding alternative approaches, the following options were considered:

- The possibility of moving packageMetadata to the base class was explored. However, as this property is not universally applicable across all operations, this approach was not selected.

- Another option was to change the visibility of the internal class to public. This was also not pursued, as it would disrupt the established pattern and potentially introduce inconsistencies.

Open for suggestions if any.

2024-05-29 16:07 UTC, Annautiy commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/MarketGroupPackageMetadata.cs
> +    public Dictionary<string, object> JsonExtensionData { get; set; }
On it, will change to named properties

2024-05-29 16:09 UTC, Annautiy commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/MarketGroupPackageMetadata.cs
> +    [JsonExtensionData]
Was using how it is implemented in package service. But got your point here it should be well defined contract in public. Moving away from same.

2024-05-29 16:10 UTC, Annautiy commented on src/PackageUploader.ClientApi/IPackageUploaderService.cs
> +    Task<GamePackageConfiguration> SetXvcAvailabilityDateAndPackageMetadataAsync(GameProduct product, IGamePackageBranch packageBranch, GamePackage gamePackage, string marketGroupName, GamePackageDat
So, packageMetadata currently only support preDownloadDate. But can have any other properties also in future. Thus, same was added

2024-05-29 16:10 UTC, Annautiy commented on src/PackageUploader.ClientApi/IPackageUploaderService.cs
> +    Task<GamePackageConfiguration> ImportPackagesAsync(GameProduct product, IGamePackageBranch originPackageBranch, IGamePackageBranch destinationPackageBranch, string marketGroupName, bool overwrite
So, packageMetadata currently only support preDownloadDate. But can have any other properties also in future. Thus, same was added

2024-05-29 16:15 UTC, Annautiy commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +    public async Task<GamePackageConfiguration> SetXvcAvailabilityDateAndPackageMetadataAsync(GameProduct product, IGamePackageBranch packageBranch, GamePackage gamePackage, string marketGroupName, G
As per exiting pattern all these configurations' classes are internal classes and can't be used here. Please do update if I should update same pattern.

2024-05-29 20:19 UTC, Annautiy commented on src/PackageUploader.Application/Config/ImportPackagesOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
Moved preDownload gate to GamePackageDate, in MarketGroupPackageMetadataConfig

2024-05-29 20:19 UTC, Annautiy commented on src/PackageUploader.Application/Config/UploadXvcPackageOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
Moved preDownload gate to GamePackageDate, in MarketGroupPackageMetadataConfig

2024-05-29 20:20 UTC, Annautiy commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/MarketGroupPackageMetadata.cs
> +    public Dictionary<string, object> JsonExtensionData { get; set; }
Moved to MarketGroupPackageMetadataConfig having strong contract

2024-05-29 20:20 UTC, Annautiy commented on src/PackageUploader.ClientApi/IPackageUploaderService.cs
> +    Task<GamePackageConfiguration> SetXvcAvailabilityDateAndPackageMetadataAsync(GameProduct product, IGamePackageBranch packageBranch, GamePackage gamePackage, string marketGroupName, GamePackageDat
Added support for GamePackageDate preDownloadDate within MarketGroupPackageMetadata

2024-05-29 20:21 UTC, Annautiy commented on src/PackageUploader.ClientApi/IPackageUploaderService.cs
> +    Task<GamePackageConfiguration> ImportPackagesAsync(GameProduct product, IGamePackageBranch originPackageBranch, IGamePackageBranch destinationPackageBranch, string marketGroupName, bool overwrite
Added support for GamePackageDate preDownloadDate within MarketGroupPackageMetadata

2024-05-29 20:25 UTC, Annautiy commented on src/PackageUploader.ClientApi/Client/Ingestion/Models/MarketGroupPackageMetadata.cs
> +    [JsonExtensionData]
Not applicable with latest code.

2024-05-30 12:34 UTC, alberto-baron commented
@Annautiy I have created a branch so you can see what I was referring to in the comments
I created a [PR here](https://github.com/microsoft/PackageUploader/pull/48) you can merge to yours if you want

2024-05-31 09:00 UTC, alberto-baron requested changes
only documentation issues

2024-05-31 09:00 UTC, alberto-baron commented on Operations.md
> +- **packageMetadata**: optional - if informed it will configure custom metadata for your XVC/MSIXVC packages. It supports the following properties
I know what you mean but this tool configuration should use concrete properties and classes.

Also dates are already exposed using a pattern, even if new metadata is added, in the partner center website the preRelease Date is just under the availability date, which should make its placement in the config be similar, and wrapping it may confuse users.

2024-05-31 09:00 UTC, alberto-baron commented on src/PackageUploader.Application/Config/ImportPackagesOperationConfig.cs
> +    public IDictionary<string, object> PackageMetadata { get; set; }
After looking at the PartnerCentre website, the preReleaseDate is grouped together with the availabilityDate.
Since we want people to relate website and json config, the structure should be similar.
Adding validation to check the date is set before availability date like the one there is in the UI is also a win

2024-05-31 09:00 UTC, alberto-baron commented on Operations.md
> +   - **isEnabled**: optional (default false) - it will enable/disable custom availability date
here it should read preDownload date

2024-05-31 09:00 UTC, alberto-baron commented on Operations.md
> +   - **effectiveDate**: optional - if informed it will set the package availability date (date format example: "2021-10-24T21:00:00.000Z")
here it should read preDownload date

2024-05-31 09:00 UTC, alberto-baron commented on Operations.md
> +   - **effectiveDate**: optional - if informed it will set the package availability date (date format example: "2021-10-24T21:00:00.000Z")
here it should read preDownload date

2024-05-31 09:00 UTC, alberto-baron commented on Operations.md
> +   - **isEnabled**: optional (default false) - it will enable/disable custom availability date
here it should read preDownload date

2024-05-31 09:00 UTC, alberto-baron commented on templates/ImportPackages.json
> +  "packageMetadata": {
preDownloadDate is not under packageMetadata anymore

2024-05-31 09:00 UTC, alberto-baron commented on templates/UploadXvcPackage.json
> +  "packageMetadata": {
preDownloadDate is not under packageMetadata anymore

2024-05-31 10:54 UTC, Annautiy commented on templates/ImportPackages.json
> +  "packageMetadata": {
Changed

2024-05-31 10:55 UTC, Annautiy commented on templates/UploadXvcPackage.json
> +  "packageMetadata": {
Changed

2024-05-31 10:55 UTC, Annautiy commented on Operations.md
> +   - **effectiveDate**: optional - if informed it will set the package availability date (date format example: "2021-10-24T21:00:00.000Z")
Changed

2024-05-31 10:55 UTC, Annautiy commented on Operations.md
> +   - **effectiveDate**: optional - if informed it will set the package availability date (date format example: "2021-10-24T21:00:00.000Z")
Changed

2024-05-31 10:55 UTC, Annautiy commented on templates/UploadXvcPackage.json
> +  "packageMetadata": {
Changed

2024-05-31 10:55 UTC, Annautiy commented on Operations.md
> +   - **isEnabled**: optional (default false) - it will enable/disable custom availability date
Changed

2024-06-04 18:11 UTC, Annautiy commented
@alberto-baron - Could you please approve, if everything looks fine.

2024-06-06 16:41 UTC, alberto-baron commented
> @alberto-baron - Could you please approve, if everything looks fine.

Hey, I can still see two pending issues.

2024-06-06 17:59 UTC, Annautiy commented
> > @alberto-baron - Could you please approve, if everything looks fine.
> 
> Hey, I can still see two pending issues.


Is the issue, which you are referring is-

**_optional (default is equivalent to availabilityDate)_**

Same was added as FYI to publisher, I can remove same if it seems like extra.


if the above one is not the issue, could you reopen the conversation which I have resolved and is still unresolved as I am somehow unable to found same.

2024-06-07 08:11 UTC, alberto-baron requested changes

2024-06-07 08:11 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
instead of default we should return the packageconfiguration from line 279

2024-06-07 08:11 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
instead of default we should return the packageconfiguration from line 279

2024-06-07 08:11 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
this is still pending

2024-06-07 08:11 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
this is still pending

2024-06-07 08:11 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
@Annautiy these issues

2024-06-07 08:11 UTC, alberto-baron commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
@Annautiy these issues

2024-06-07 09:01 UTC, Annautiy commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
Thanks for catching this, as I have introduced a bug where I have started returning directly rather than updating. Moved to old code to resolve same.

2024-06-07 09:02 UTC, Annautiy commented on src/PackageUploader.ClientApi/PackageUploaderService.cs
> +            return default;
Thanks for catching this, as I have introduced a bug where I have started returning directly rather than updating in last line. Moved to old way to resolve same.

2024-06-10 09:46 UTC, alberto-baron approved these changes

2024-06-10 18:15 UTC, merged